### ISSUE TITLE
怎么跑起来

### ISSUE THREAD

**Issue by LonelyFellas** [message163/various-devices#10]
<img width="1153" alt="image" src="https://github.com/message163/various-devices/assets/38754760/989e0ff3-6295-46ab-ba0e-ba71b22260dc">

**Comment by message163** [comment]
你用的是什么镜像呢

**Comment by LonelyFellas** [comment]
@message163  怎么讲呢。我觉得你推荐一个镜像并且写在README.md.

**Comment by core-admin** [comment]
node v18.18.2 npm install 没问题，我刚开始也存在依赖安装问题，后删除node_modules 和 lock文件，安装成功了
